name: Fuzzing
on:
  workflow_dispatch:

jobs:
  fuzzing:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Project
        uses: ./.github/actions/Desktop-build
        with:
          compiler: llvm
          cmake_flags: '-DCMAKE_CXX_FLAGS="-fsanitize=address" -DFUZZ_TEST=ON -DLINK_TIME_OPT=OFF'

      - name: Prepare directories
        shell: bash
        run: mkdir -p corpus

      - name: Fuzz
        run: .\build\tests\fuzz\fuzz_tests.exe corpus -runs=1000 -max_total_time=120

      - name: Upload Fuzz Executable
        uses: actions/upload-artifact@v4
        with:
          name: fuzz_tests
          path: .\build\tests\fuzz\fuzz_tests.exe
          retention-days: 1